### ISSUE TITLE
Theme color not working for Tab component 

### ISSUE THREAD

**Issue by cb-tinjothomas** [cb-jayaraje/sting#7]
![image](https://user-images.githubusercontent.com/106964049/185045164-0737e4c4-b80f-4a1d-b2bc-1744b0e239f4.png)

**Comment by cb-jayaraje** [comment]
Thanks for pointing out @cb-tinjothomas some colors are not connected to the theme, work is still in progress

**Comment by cb-jayaraje** [comment]
Cleared
